---
title: "Advanced statistical methods | UE-L25.01477"
author: "Bernhard Piskernik"
date: "2022/09/22"
output: 
  ioslides_presentation:
        css: ../style.css
        incremental: true
---

```{r setup, include=FALSE}
library(tidyverse)
library(plotly)
library(kableExtra)
options(warn=-1)
```

## Objectives of this course {.build}

* refresh your statistical knowledge
* learn some new methods and techniques
* compare different methods for the same problem
* discuss how to decide on the best statistical method for the given problem
* see some statistical analyses in action


## Rules

* if you have a question - ask!
* don't expect me to be able to give a clear-cut answer (each time)


## Procedure

* mostly online
* I have prepared some slides
  - with information
  - with analyses
  - (all slides are written in R - if there is an example, then the data and all analyses are in there)
  
* I will ask questions
* hopefully, you will too
* there will be homework (partially graded)


## What this course is not?

* an R course (but I can recommend [R for Data Science](https://r4ds.had.co.nz/) by H. Wickham)
* a coding course - all code is there, but you don't need to memorize it
* a coverage of all "advanced" statistical methods


## Grades

* test at the end of the semester [80%]
* graded homework [20%]


## Timetable | attention: not each week

* 22.09. start
* 06.10. mean differences of groups I
* 13.10. mean differences of groups II (**NOT** online)
* 03.11. multiple regression
* 17.11. nested data
* 01.12. _your pick I_
* 15.12. _your pick II_
* 22.12. optional: bring your (methodical) problem

## Your picks | voting in Moodle until 13.10.

* missing data
* generalized linear model
* ordinal data in regressions
* nested data (a deeper dive)
* finding groups in data
* dimensionality reduction
* path models
* write me until tomorrow for the addition of further options


## Resources

* all my materials for this course can be found at the git hub repo [bpiskernik/2022_SA_advanced_statistical_methods](https://github.com/bpiskernik/2022_SA_advanced_statistical_methods) 
* the slides will be in moodle
* the slides contain links to additional material (for those who are interested)


## Homework | **NOT** graded

* install R
* install RStudio
* install [Tidyverse](https://www.tidyverse.org/) in RStudio
* skip through [R for Data Science](https://r4ds.had.co.nz/)
